### PR TITLE
Update Cards Styles

### LINKED ISSUE #34: Uneven grid distribution in `People` Page
I noticed several non uniform grid distributions in the page `peoples.js` which rendered image cards mainly on the basis of provided URLs in `contributors.js`. Is there any way we can modify the grid distribution to reduce gaps and improve the UI ?
Following are some views I found odd for the UI : 
Screenshot 2024-01-02 at 11 45 25 AM
Screenshot 2024-01-02 at 11 45 13 AM

### PR DESCRIPTION
**Pull request by Sweetdevil144**
Fixes #34  
Refactor layout for responsive design :
- Implement two-column layout for larger screens
- Switch to single-column on smaller devices for better usability

### CODE REVIEW

**Comment by eshantri** [comment]
@GandalfGwaihir will review and test this locally by Friday.  Thanks!

**Comment by eshantri** [comment]
@Sweetdevil144 can you post a screenshot/gif of the result? Would be helpful.

**Comment by eshantri** [comment]
@GandalfGwaihir @Sweetdevil144  I tested the code locally, the grid issue is still there, along with weird arrangement of cards.

**Comment by Sweetdevil144** [comment]
> @Sweetdevil144 can you post a screenshot/gif of the result? Would be helpful.

Hey can you review this drive link to a video clips showing how the grid layout was laid out as I described. I think it works fine and the problem of irregular spacing is removed : https://drive.google.com/file/d/1T9uxoM4vti7ngUt3iD8P_SPqD_Ee3bc6/view?usp=sharing

It is also responsive for smaller screen size as shown in the video in this drive link : https://drive.google.com/file/d/1AijsMudf1ekRhXk8UlR8sm_HzHwGOf-2/view?usp=sharing

**Comment by Sweetdevil144** [comment]
> @GandalfGwaihir @Sweetdevil144 I tested the code locally, the grid issue is still there, along with weird arrangement of cards.

The goal of this issue (#34) was to remove irregular spacing between two card rowsehich was caused due to card layout. Can you explain a bit more with any 'image' example of what more changes would you like to be made for this? I'll improve the PR accordingly. @GandalfGwaihir can you checkout the drive links till then?

**Comment by Sweetdevil144** [comment]
@GandalfGwaihir and @eshantri . Did you verify it?

**Comment by eshantri** [comment]
Will verify this in a while.

**Comment by Sweetdevil144** [comment]
Cannot attach video_size>10mb, so attaching it via drive links.
Updated custom card size to make it uniform : [Link](https://drive.google.com/file/d/1qihlYcOHmCGfc4mR5UBurnAMD1U_R0M5/view?usp=sharing)

**Comment by eshantri** [comment]
Mwerging this. Thanks @Sweetdevil144 @GandalfGwaihir .

**Pull request merged**
