### PR TITLE
updated docusaurus.config to run locally

### PR DESCRIPTION
**Pull request by Veer0x1**

### CODE REVIEW

**Comment by dlebauer** [comment]
Thank you for submitting this PR! Can you please explain how these changes help? Why such a large diff in the .lock file?

**Comment by vaishnavi4444** [comment]
Thanks for recommending this change!

**Comment by Veer0x1** [comment]
In the new version of docusaurus we can't write in this format,` hideableSidebar: true` is a property of the doc object; I commented on this line because, as of now we don't have a doc folder in the root directory; so this will not create issue while setting up a development environment.

if someone is interested in creating the docs folder, then he can replace that commented line with ```
docs: {
      sidebar: {
        autoCollapseCategories: true,
        hideable: true,
      },
    }
``` this will work for that case

**Comment by Veer0x1** [comment]
In the new version of docusaurus we can't write in this format,` hideableSidebar: true` is a property of the doc object; I commented on this line because, as of now we don't have a doc folder in the root directory; so this will not create issue while setting up a development environment.

if someone is interested in creating the docs folder, then he can replace that commented line with ```
docs: {
      sidebar: {
        autoCollapseCategories: true,
        hideable: true,
      },
    }
``` this will work for that case

**Comment by Veer0x1** [comment]
In the new version of docusaurus we can't write in this format,` hideableSidebar: true` is a property of the doc object; I commented on this line because, as of now we don't have a doc folder in the root directory; so this will not create issue while setting up a development environment.

if someone is interested in creating the docs folder, then he can replace that commented line with ```
docs: {
      sidebar: {
        autoCollapseCategories: true,
        hideable: true,
      },
    }
``` this will work for that case

**Comment by Veer0x1** [comment]
In the new version of docusaurus we can't write in this format,` hideableSidebar: true` is a property of the doc object; I commented on this line because, as of now we don't have a doc folder in the root directory; so this will not create issue while setting up a development environment.

if someone is interested in creating the docs folder, then he can replace that commented line with ```
docs: {
      sidebar: {
        autoCollapseCategories: true,
        hideable: true,
      },
    }
``` this will work for that case

**Pull request closed without merging**
